/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaDietary;

import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

import java.awt.Color;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author febri
 */
public class BMI extends javax.swing.JFrame implements DietaryCalculations{

    /**
     * Creates new form BMI
     */
    public BMI() {
        initComponents();
        customizeUI();
    }

    private void customizeUI() {
        getContentPane().setBackground(new Color(236, 227, 206));

        ButtonKembali.setBackground(new Color(79, 111, 82));
        BMIButton.setBackground(new Color(79, 111, 82));
        logoutButton.setBackground(new Color(79, 111, 82));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tinggiField = new javax.swing.JTextField();
        beratField = new javax.swing.JTextField();
        usiaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jkComboBox = new javax.swing.JComboBox<>();
        ButtonKembali = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        BMIButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tinggi (cm):");

        jLabel2.setText("Berat (kg):");

        jLabel3.setText("Usia:");

        tinggiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kelamin:");

        jkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pria", "Wanita" }));

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        BMIButton.setText("Hitung BMI");
        BMIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMIButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                        .addComponent(tinggiField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beratField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jkComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonKembali)
                                .addGap(18, 18, 18)
                                .addComponent(BMIButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tinggiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(beratField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonKembali)
                    .addComponent(BMIButton))
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tinggiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiFieldActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        ShowLogin login = new ShowLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    // fungsi multithread
    private void BMIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMIButtonActionPerformed
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                double tinggi = Double.parseDouble(tinggiField.getText());
                double berat = Double.parseDouble(beratField.getText());
                int usia = Integer.parseInt(usiaField.getText());
                String gender = (String) jkComboBox.getSelectedItem();

                double bmi = calculateBMI(tinggi, berat);
                String status = getStatusBMI(bmi, gender, usia);

                JOptionPane.showMessageDialog(null, "BMI Anda: " + bmi + "\nStatus: " + status);

                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                } catch (InterruptedException | ExecutionException ex) {
                    ex.printStackTrace();
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_BMIButtonActionPerformed
    
    @Override
    public double calculateBMI(double height, double weight) {
        return weight / Math.pow(height / 100, 2);
    }

    @Override
    public String getStatusBMI(double bmi, String gender, int usia) {
        if (gender.equals("Pria")) {
            return getStatusPria(bmi, usia);
        } else {
            return getStatusWanita(bmi, usia);
        }
    }
    private String getStatusPria(double bmi, int usia) {
        if (usia < 30) {
            if (bmi < 18.5) {
                return "Kurus";
            } else if (bmi >= 18.5 && bmi < 24.9) {
                return "Normal";
            } else if (bmi >= 25 && bmi < 29.9) {
                return "Gendut";
            } else {
                return "Obesitas";
            }
        } else {
            if (bmi < 18.5) {
                return "Kurus";
            } else if (bmi >= 18.5 && bmi < 24.9) {
                return "Normal";
            } else if (bmi >= 25 && bmi < 29.9) {
                return "Gendut";
            } else {
                return "Obesitas";
            }
        }
    }
    
    private String getStatusWanita(double bmi, int usia) {
        if (usia < 25) {
            if (bmi < 18.5) {
                return "Kurus";
            } else if (bmi >= 18.5 && bmi < 24.9) {
                return "Normal";
            } else if (bmi >= 25 && bmi < 29.9) {
                return "Gendut";
            } else {
                return "Obesitas";
            }
        } else {
            if (bmi < 18.5) {
                return "Kurus";
            } else if (bmi >= 18.5 && bmi < 24.9) {
                return "Normal";
            } else if (bmi >= 25 && bmi < 29.9) {
                return "Gendut";
            } else {
                return "Obesitas";
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BMIButton;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JTextField beratField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jkComboBox;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField tinggiField;
    private javax.swing.JTextField usiaField;
    // End of variables declaration//GEN-END:variables
}
